/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import ckeditor from "@ckeditor/strapi-plugin-ckeditor/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import documentation from "@strapi/plugin-documentation/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import routePermission from "strapi-plugin-server-route-permission/strapi-admin";
import tgauth from "../../src/plugins/tgauth/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    ckeditor: ckeditor,
    "strapi-cloud": strapiCloud,
    documentation: documentation,
    i18n: i18N,
    "users-permissions": usersPermissions,
    "route-permission": routePermission,
    tgauth: tgauth,
  },
});
